language: python

python:
    - '3.6.9'
    - '3.7.3'
    - '3.7.4'
    - '3.7.5'
    - '3.7.6'
    - '3.7.7'
    - '3.8.0'

os:
    - linux

cache: pip

before_install:
    - pip3 install -U pip

install:
    - python3 setup.py install

script:
    - pytest
